### ISSUE TITLE
invalid : gcolor3.appdata.xml.in

### ISSUE THREAD

**Issue by Fnux** [Hjdskes/gcolor3#60]
When running appstream-util for validation of `gcolor3.appdata.xml` :
```
gcolor3/data [master] » appstream-util validate gcolor3.appdata.xml.in 
gcolor3.appdata.xml.in: FAILED:
• url-not-found         : <screenshot> url not found [https://raw.githubusercontent.com/Hjdskes/hjdskes.github.io/hugo/static/images/projects/gcolor3/saved.png]
• url-not-found         : <screenshot> url not found [https://raw.githubusercontent.com/Hjdskes/hjdskes.github.io/hugo/static/images/projects/gcolor3/picker.png]
Validation of files failed
```

Aside from the broken link, is there a reason for those two files not to be included in the repo ?

**Comment by Hjdskes** [comment]
Thanks for the report. I'll add the screenshots to the repo this weekend.

**Comment by Fnux** [comment]
`https://github.com/Hjdskes/gcolor3/blob/master/saved.png` is not an image !

Moreover, I don't think that an url to the master branch is a 'safe' place... ?

**Comment by Hjdskes** [comment]
> `https://github.com/Hjdskes/gcolor3/blob/master/saved.png` is not an image !

I accidentally committed this link but I fixed it with an amend; are you sure you're checking the most up-to-date version? The version in master shows the correct urls: https://github.com/Hjdskes/gcolor3/blob/master/data/gcolor3.appdata.xml.in#L32

> Moreover, I don't think that an url to the master branch is a 'safe' place... ?

Maybe not with respect to possible changes to the UI in future versions, but AFAIK screenshots per version aren't supported by the appdata format so that doesn't apply here. Why would the master branch not be a safe place, and what would you suggest instead?

**Comment by Fnux** [comment]
Well, if you decide to restructure and move things around, change names or whatever. I would think it's better to depend on a tag/commit ?

**Comment by Hjdskes** [comment]
Sorry for the late reply. You're right; the latest commit makes the screenshot URLs point to a specific commit.
