### ISSUE TITLE
CTRL-C / CTRL-V doesn't work properly.

### ISSUE THREAD

**Issue by dasnoopy** [Hjdskes/gcolor3#64]
Hi, just noticed this issue since a while using Gcolor3 compiler from git master on Archlinux.

1)  Open the app and choose any color you want
2) highlight the content of "color name" field
3) press  CTRL-C / CTRL-V (via keyboard)  to copy/paste the  the value e.g. in gedit : the value #BCBCBC is always pasted insted to paste the current selected color value

Using mouse and right menu copy/paste works as expected

Thanks

**Comment by dasnoopy** [comment]
Just discovered that the value pasted is always the first color saved in the "saved colors" list : e.g. #BCBCBC was the first color in my list, then after delete it, the new first color was #747474 : trying to use ctrl-c / ctrl-v the #747474 is always pasted

**Comment by Hjdskes** [comment]
Thanks, that'll help debugging. I'm a little preoccupied at the moment so don't expect a fix soon.

**Comment by orschiro** [comment]
I have the same as @diamondburned on Fedora 28 with version 2.2. Pressing Ctrl + c on the keyboard doesn't copy it. Right mouse click approach works. 

Can this be fixed easily @Hjdskes?

**Comment by jtojnar** [comment]
The issue is that there is a global action associated with <kbd>ctrl</kbd>-<kbd>c</kbd>:

https://github.com/Hjdskes/gcolor3/blob/c011b013ec8221a697df62158b48fa87c9e6a42f/src/gcolor3-application.c#L100

We could disable it like this:

https://github.com/jtojnar/gcolor3/commit/958479adaf566c0150d4e42e32a1b4100195f048

But then there is the same issue as with `delete` action, that needs to be fixed as well:

https://github.com/jtojnar/gcolor3/commit/4777d67774778c42d6c0dcfa13cbbd7e2eba6d5f

Worst of all, the issue would still persist on the “Saved colours” page (e.g. if you want to copy the colour name). We could try to fix it by disabling the action whenever a `TreeView` cell is edited, but who knows where this rabbit hole ends.

**Comment by Hjdskes** [comment]
Thanks for looking into this, @jtojnar. I just quickly tried your branch and everything seems to work fine. What is the rabbit hole you're describing?

**Comment by jtojnar** [comment]
Well, maybe disabling the action on [`editing-started`](https://developer.gnome.org/gtk3/stable/GtkCellRenderer.html#GtkCellRenderer-editing-started) and re-enabling it on `editing-canceled` would really be enough, but more likely, there is something else I am missing. I can fix this instance, and others as we discover them, but perhaps there is a better way.
